USE master;

USE rebcho;

--INSERT INTO PRODUCT
--VALUES ('MOD2', 'B', 'PRINTER');

SELECT * FROM PRODUCT;

--INSERT INTO PRINTER
--VALUES (2, 'MOD1', 45.74);

--ALTER TABLE PRINTER
--ADD TYPEIS VARCHAR(6) NOT NULL DEFAULT 'JET';

--ALTER TABLE PRINTER
--ADD COLOUR CHAR(1) NOT NULL DEFAULT 'N';

--ALTER TABLE PRINTER
--DROP COLUMN PRICE;

SELECT * FROM PRINTER;

DROP TABLE PRINTER, PRODUCT;
