-USE rebcho;


--INSERT INTO FRIENDS
--VALUES ('(10,21)'),
-- ('(15,10)'),
-- ('(21,15)');

--SELECT * FROM FRIENDS;

--INSERT INTO WALLS
--VALUES (15, 21, 'YOU ARE MY FRIEND NOW!', '2025-02-15'),
-- (15, 21, 'WE ARE FRIENDS FOR A LONG TIME NOW!', '2010-06-06');
--SELECT * FROM WALLS;

--INSERT INTO USERS
--VALUES ('BANANAS@GMAIL.COM', 'KJWEFFJUWRE', '2025-04-15'),
-- ('ANANAS@GMAIL.COM', 'GREWFG', '2025-03-15');

--SELECT * FROM USERS;

--INSERT INTO GROUPS
--VALUES('FRIUTS', 'BANANAS AND ANANAS'),
-- ('FRIENDS', '')
--SELECT *  FROM GROUPS;

--INSERT INTO GROUPMEMBERS
--VALUES ('(FRUITS,15)'),
-- ('(FRIENDS,21)')

--SELECT * FROM GROUPSMEMBERS;
