USE master
GO

USE FLIGHTS
GO

CREATE TABLE AIRLINE(
CODE INT NOT NULL CONSTRAINT PK_AIRLINE_CODE PRIMARY KEY,
NAME VARCHAR(256) NOT NULL UNIQUE,
COUNTRY VARCHAR(256),
);

CREATE TABLE AIRPORT(
CODE INT NOT NULL CONSTRAINT PK_AIRPORT_CODE PRIMARY KEY,
NAME VARCHAR(256) NOT NULL,
COUNTRY VARCHAR(256),
TOWN VARCHAR(256),
CONSTRAINT YK_NAME_COUNTRY UNIQUE (NAME, COUNTRY)
);

CREATE TABLE FLIGHT(
FNUMBER INT NOT NULL CONSTRAINT PK_FLIGHT_NUMBER PRIMARY KEY,
AIRLINE_OPERATOR INT NOT NULL CONSTRAINT FK_AIRLINE_OPERATOR REFERENCES AIRLINE(CODE),
DEP_AIRPORT INT NOT NULL CONSTRAINT FK_DEP_AIRPORT REFERENCES AIRPORT(CODE),
ARR_AIRPORT INT NOT NULL CONSTRAINT FK_ARR_AIRPORT REFERENCES AIRPORT(CODE),
FLIGHT_TIME TIME,
FLIGHT_DURATION INT,
AIRPLANE INT
);

CREATE TABLE AIRPLANE(
CODE INT NOT NULL CONSTRAINT PK_AIRPLANE_CODE PRIMARY KEY,
TYPE VARCHAR(256),
SEATS_COUNT INT,
PLANE_YEAR INT,
CONSTRAINT FK_FLIGHT_NUMBER FOREIGN KEY(CODE) REFERENCES FLIGHT(FNUMBER),
CHECK(SEATS_COUNT > 0)
);


CREATE TABLE CUSTOMER(
ID INT NOT NULL CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY,
FNAME VARCHAR(256),
LNAME VARCHAR(256),
EMAIL VARCHAR(256) CHECK(EMAIL LIKE '%@%.%')
);

CREATE TABLE AGENCY(
ANAME VARCHAR(256) NOT NULL CONSTRAINT PK_AGENCY_NAME PRIMARY KEY,
COUNTRY VARCHAR(256),
CITY VARCHAR(256),
PHONE VARCHAR(10)
);

CREATE TABLE BOOKING(
CODE INT NOT NULL CONSTRAINT PK_BOOKING_CODE PRIMARY KEY,
AGENCY VARCHAR(256) CONSTRAINT FK_AGENCY REFERENCES AGENCY(ANAME),
AIRLINE_CODE INT
CONSTRAINT FK_BOOKING_AIRLINE REFERENCES AIRLINE(CODE),
FLIGHT_NUMBER INT CONSTRAINT FK_FNUMBER REFERENCES FLIGHT(FNUMBER),
CUSTOMER_ID INT CONSTRAINT FK_CUSTOMER_ID REFERENCES CUSTOMER(ID),
BOOKING_DATE DATETIME,
FLIGHT_DATE DATETIME,
PRICE FLOAT,
FSTATUS CHAR CHECK (FSTATUS IN ('0', '1')),
CHECK(FLIGHT_DATE >= BOOKING_DATE)
);
